-- =====================================================================
-- (주)장인의공간 홈페이지 - MySQL 스키마
--
-- 1) TBL_SYS_*  : 시스템/권한 테이블. osca 프로젝트와 동일한 구조로,
--                 사용자관리 / 권한관리 / 사용자권한관리 / 메뉴관리 /
--                 프로그램관리 / 권한별메뉴관리 화면을 그대로 이식하기 위한 것이다.
-- 2) TBL_HP_*   : 홈페이지 콘텐츠 테이블. 레거시 PHP 의 tb_inquiry / tb_history /
--                 tb_project / tb_category / tb_file / tb_yark 에서
--                 실제 화면이 사용하는 컬럼만 추려 정규화했다.
--
-- 대상: MySQL 5.6 (레거시 서버와 동일)
--   - 엔진은 전부 InnoDB. 관리자 저장이 트랜잭션으로 처리되므로 MyISAM 을 쓰지 않는다.
--     (레거시는 전 테이블 MyISAM 이라 트랜잭션·외래키가 없었다)
--   - 5.6 은 CHECK 제약을 무시하므로 Y/N 값은 ENUM 으로 강제한다.
--   - utf8mb4 + InnoDB 인덱스 접두 한계(767바이트)를 넘지 않도록 키 컬럼은 짧게 잡았다.
--
-- 실행:  mysql -h <host> -u <user> -p <db> < db/schema.sql
-- =====================================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ---------------------------------------------------------------------
-- 1. 시스템 / 권한
-- ---------------------------------------------------------------------

-- 사용자
CREATE TABLE IF NOT EXISTS TBL_SYS_USER (
  USER_ID         VARCHAR(30)  NOT NULL                COMMENT '로그인 아이디',
  USER_NM         VARCHAR(50)  NOT NULL                COMMENT '사용자명',
  USER_PWD        VARCHAR(100) NOT NULL                COMMENT '비밀번호(bcrypt 해시)',
  USER_EML        VARCHAR(200) NULL                    COMMENT '이메일',
  USE_YN          ENUM('Y','N') NOT NULL DEFAULT 'Y'   COMMENT '사용여부',
  APR_YN          ENUM('Y','N') NOT NULL DEFAULT 'N'   COMMENT '승인여부',
  APR_ID          VARCHAR(30)  NULL                    COMMENT '승인자',
  FRST_REG_DT     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FRST_REGR_EMPNO VARCHAR(30)  NULL,
  LST_CHG_DT      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  LST_CHGR_EMPNO  VARCHAR(30)  NULL,
  PRIMARY KEY (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='사용자';

-- 사용자 접속 이력
CREATE TABLE IF NOT EXISTS TBL_SYS_USER_HST (
  HST_SQNO        BIGINT       NOT NULL AUTO_INCREMENT,
  USER_ID         VARCHAR(30)  NOT NULL,
  CNN_IP          VARCHAR(45)  NULL                    COMMENT '접속 IP(IPv6 대응)',
  FRST_REG_DT     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FRST_REGR_EMPNO VARCHAR(30)  NULL,
  LST_CHG_DT      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  LST_CHGR_EMPNO  VARCHAR(30)  NULL,
  PRIMARY KEY (HST_SQNO),
  KEY IX_SYS_USER_HST_01 (USER_ID, FRST_REG_DT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='사용자 접속 이력';

-- 권한
CREATE TABLE IF NOT EXISTS TBL_SYS_AUTH (
  AUTH_ID         VARCHAR(20)  NOT NULL                COMMENT '권한 아이디(ADMIN, MNGR 등)',
  AUTH_NM         VARCHAR(50)  NOT NULL                COMMENT '권한명',
  USE_YN          ENUM('Y','N') NOT NULL DEFAULT 'Y',
  FRST_REG_DT     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FRST_REGR_EMPNO VARCHAR(30)  NULL,
  LST_CHG_DT      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  LST_CHGR_EMPNO  VARCHAR(30)  NULL,
  PRIMARY KEY (AUTH_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='권한';

-- 사용자별 권한
CREATE TABLE IF NOT EXISTS TBL_SYS_USER_AUTH (
  USER_ID         VARCHAR(30)  NOT NULL,
  AUTH_ID         VARCHAR(20)  NOT NULL,
  FRST_REG_DT     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FRST_REGR_EMPNO VARCHAR(30)  NULL,
  LST_CHG_DT      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  LST_CHGR_EMPNO  VARCHAR(30)  NULL,
  PRIMARY KEY (USER_ID, AUTH_ID),
  KEY IX_SYS_USER_AUTH_01 (AUTH_ID),
  CONSTRAINT FK_SYS_USER_AUTH_01 FOREIGN KEY (USER_ID) REFERENCES TBL_SYS_USER (USER_ID) ON DELETE CASCADE,
  CONSTRAINT FK_SYS_USER_AUTH_02 FOREIGN KEY (AUTH_ID) REFERENCES TBL_SYS_AUTH (AUTH_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='사용자별 권한';

-- 프로그램 (화면 경로)
CREATE TABLE IF NOT EXISTS TBL_SYS_PGM (
  PGM_ID          VARCHAR(30)  NOT NULL                COMMENT '프로그램 아이디',
  PGM_NM          VARCHAR(100) NOT NULL                COMMENT '프로그램명',
  PGM_PTH_NM      VARCHAR(255) NOT NULL                COMMENT '라우트 경로',
  FRST_REG_DT     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FRST_REGR_EMPNO VARCHAR(30)  NULL,
  LST_CHG_DT      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  LST_CHGR_EMPNO  VARCHAR(30)  NULL,
  PRIMARY KEY (PGM_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='프로그램';

-- 메뉴 (3단계 트리)
CREATE TABLE IF NOT EXISTS TBL_SYS_MENU (
  MENU_ID         VARCHAR(30)  NOT NULL                COMMENT '메뉴 아이디',
  MENU_NM         VARCHAR(100) NOT NULL                COMMENT '메뉴명',
  UPPO_MENU_ID    VARCHAR(30)  NULL                    COMMENT '상위 메뉴 아이디',
  PGM_ID          VARCHAR(30)  NULL                    COMMENT '연결 프로그램',
  MENU_STEP       ENUM('1','2','3') NOT NULL           COMMENT '메뉴 단계',
  MENU_SEQO       INT          NULL                    COMMENT '정렬 순서',
  PARM_CTT        VARCHAR(255) NULL                    COMMENT '쿼리스트링 파라미터',
  USE_YN          ENUM('Y','N') NOT NULL DEFAULT 'Y',
  FRST_REG_DT     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FRST_REGR_EMPNO VARCHAR(30)  NULL,
  LST_CHG_DT      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  LST_CHGR_EMPNO  VARCHAR(30)  NULL,
  PRIMARY KEY (MENU_ID),
  KEY IX_SYS_MENU_01 (MENU_STEP, UPPO_MENU_ID, MENU_SEQO),
  KEY IX_SYS_MENU_02 (PGM_ID),
  CONSTRAINT FK_SYS_MENU_01 FOREIGN KEY (PGM_ID) REFERENCES TBL_SYS_PGM (PGM_ID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='메뉴';

-- 권한별 메뉴
CREATE TABLE IF NOT EXISTS TBL_SYS_AUTH_MENU (
  AUTH_ID         VARCHAR(20)  NOT NULL,
  MENU_ID         VARCHAR(30)  NOT NULL,
  FRST_REG_DT     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FRST_REGR_EMPNO VARCHAR(30)  NULL,
  LST_CHG_DT      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  LST_CHGR_EMPNO  VARCHAR(30)  NULL,
  PRIMARY KEY (AUTH_ID, MENU_ID),
  KEY IX_SYS_AUTH_MENU_01 (MENU_ID),
  CONSTRAINT FK_SYS_AUTH_MENU_01 FOREIGN KEY (AUTH_ID) REFERENCES TBL_SYS_AUTH (AUTH_ID) ON DELETE CASCADE,
  CONSTRAINT FK_SYS_AUTH_MENU_02 FOREIGN KEY (MENU_ID) REFERENCES TBL_SYS_MENU (MENU_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='권한별 메뉴';

-- ---------------------------------------------------------------------
-- 2. 홈페이지 콘텐츠
-- ---------------------------------------------------------------------

-- 고객문의  (레거시 tb_inquiry)
--   INQ_FLD_NM <- title          (문의분야)
--   CO_NM      <- field_etc_01   (회사명)
--   PSTN_NM    <- field_etc_02   (직함)
CREATE TABLE IF NOT EXISTS TBL_HP_INQUIRY (
  INQ_SQNO        BIGINT       NOT NULL AUTO_INCREMENT,
  INQ_FLD_NM      VARCHAR(255) NOT NULL                COMMENT '문의분야',
  CO_NM           VARCHAR(255) NULL                    COMMENT '회사명',
  PSTN_NM         VARCHAR(255) NULL                    COMMENT '직함',
  WRTR_NM         VARCHAR(50)  NOT NULL                COMMENT '이름',
  WRTR_TELNO      VARCHAR(30)  NOT NULL                COMMENT '연락처',
  WRTR_EML        VARCHAR(250) NOT NULL                COMMENT '이메일',
  INQ_CTT         TEXT         NOT NULL                COMMENT '문의내용',
  PRVC_AGRE_DT    DATETIME     NOT NULL                COMMENT '개인정보 수집 동의 시각',
  PRCS_STS_CD     ENUM('RECV','DONE') NOT NULL DEFAULT 'RECV' COMMENT '처리상태',
  RPLY_CTT        TEXT         NULL                    COMMENT '답변내용',
  RPLY_DT         DATETIME     NULL                    COMMENT '답변일시',
  RPLY_USER_ID    VARCHAR(30)  NULL                    COMMENT '답변자',
  WRTR_IP         VARCHAR(45)  NULL                    COMMENT '등록 IP',
  DEL_YN          ENUM('Y','N') NOT NULL DEFAULT 'N'   COMMENT '삭제여부(소프트 삭제)',
  FRST_REG_DT     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  LST_CHG_DT      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  LST_CHGR_EMPNO  VARCHAR(30)  NULL,
  PRIMARY KEY (INQ_SQNO),
  KEY IX_HP_INQUIRY_01 (DEL_YN, FRST_REG_DT),
  KEY IX_HP_INQUIRY_02 (WRTR_IP, FRST_REG_DT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='고객문의';

-- 연혁  (레거시 tb_history)
CREATE TABLE IF NOT EXISTS TBL_HP_HISTORY (
  HIST_SQNO       BIGINT       NOT NULL AUTO_INCREMENT,
  HIST_YR         CHAR(4)      NOT NULL                COMMENT '연도',
  HIST_MM         CHAR(2)      NOT NULL                COMMENT '월',
  HIST_CTT        TEXT         NOT NULL                COMMENT '내용',
  MENU_SEQO       INT          NOT NULL DEFAULT 999    COMMENT '정렬 순서',
  USE_YN          ENUM('Y','N') NOT NULL DEFAULT 'Y'   COMMENT '노출여부',
  FRST_REG_DT     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  LST_CHG_DT      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  LST_CHGR_EMPNO  VARCHAR(30)  NULL,
  PRIMARY KEY (HIST_SQNO),
  KEY IX_HP_HISTORY_01 (USE_YN, HIST_YR, HIST_MM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='회사 연혁';

-- 수행과제 분류  (레거시 tb_category / tablename='tb_project')
CREATE TABLE IF NOT EXISTS TBL_HP_PROJECT_CTG (
  CTG_SQNO        BIGINT       NOT NULL AUTO_INCREMENT,
  CTG_NM          VARCHAR(255) NOT NULL                COMMENT '분류명(연도 등)',
  MENU_SEQO       INT          NOT NULL DEFAULT 999,
  USE_YN          ENUM('Y','N') NOT NULL DEFAULT 'Y',
  FRST_REG_DT     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  LST_CHG_DT      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  LST_CHGR_EMPNO  VARCHAR(30)  NULL,
  PRIMARY KEY (CTG_SQNO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='수행과제 분류';

-- 수행과제  (레거시 tb_project)
--   PRJ_KND_CD <- mode          ('1' 개발 / '2' 연구 - 화면 탭)
--   CTG_SQNO   <- depth1        (연도 카테고리)
--   ORDR_NM    <- field_etc_01  (발주처)
CREATE TABLE IF NOT EXISTS TBL_HP_PROJECT (
  PRJ_SQNO        BIGINT       NOT NULL AUTO_INCREMENT,
  PRJ_KND_CD      ENUM('1','2') NOT NULL               COMMENT '과제구분 1=개발 2=연구',
  CTG_SQNO        BIGINT       NULL                    COMMENT '분류(연도)',
  PRJ_NM          VARCHAR(255) NOT NULL                COMMENT '과제명',
  PRJ_CTT         TEXT         NULL                    COMMENT '내용(줄바꿈 단위로 목록 렌더링)',
  BGNG_DE         DATE         NULL                    COMMENT '시작일',
  END_DE          DATE         NULL                    COMMENT '종료일',
  ORDR_NM         VARCHAR(255) NULL                    COMMENT '발주처',
  MENU_SEQO       INT          NOT NULL DEFAULT 999,
  USE_YN          ENUM('Y','N') NOT NULL DEFAULT 'Y',
  FRST_REG_DT     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  LST_CHG_DT      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  LST_CHGR_EMPNO  VARCHAR(30)  NULL,
  PRIMARY KEY (PRJ_SQNO),
  KEY IX_HP_PROJECT_01 (PRJ_KND_CD, CTG_SQNO, USE_YN),
  KEY IX_HP_PROJECT_02 (CTG_SQNO),
  CONSTRAINT FK_HP_PROJECT_01 FOREIGN KEY (CTG_SQNO) REFERENCES TBL_HP_PROJECT_CTG (CTG_SQNO) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='수행과제';

-- 첨부파일  (레거시 tb_file)
CREATE TABLE IF NOT EXISTS TBL_HP_ATTACH (
  ATCH_SQNO       BIGINT       NOT NULL AUTO_INCREMENT,
  REF_TBL_NM      VARCHAR(50)  NOT NULL                COMMENT '참조 테이블명',
  REF_SQNO        BIGINT       NOT NULL                COMMENT '참조 일련번호',
  ORGNL_FILE_NM   VARCHAR(255) NOT NULL                COMMENT '원본 파일명',
  STRG_FILE_NM    VARCHAR(255) NOT NULL                COMMENT '저장 파일명',
  FILE_SZ         BIGINT       NOT NULL                COMMENT '파일 크기(byte)',
  FILE_MIME       VARCHAR(100) NULL,
  DWLD_CNT        INT          NOT NULL DEFAULT 0      COMMENT '다운로드 횟수',
  MENU_SEQO       INT          NOT NULL DEFAULT 0,
  FRST_REG_DT     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ATCH_SQNO),
  KEY IX_HP_ATTACH_01 (REF_TBL_NM, REF_SQNO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='첨부파일';

-- 약관 / 개인정보처리방침  (레거시 tb_yark)
CREATE TABLE IF NOT EXISTS TBL_HP_TERM (
  TERM_SQNO       BIGINT       NOT NULL AUTO_INCREMENT,
  TERM_KND_CD     ENUM('PRIVACY','SERVICE','EMAIL') NOT NULL COMMENT '약관 종류',
  TERM_CTT        MEDIUMTEXT   NOT NULL                COMMENT '본문(HTML)',
  APLY_BGNG_DT    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '시행일',
  USE_YN          ENUM('Y','N') NOT NULL DEFAULT 'Y',
  FRST_REG_DT     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  LST_CHG_DT      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  LST_CHGR_EMPNO  VARCHAR(30)  NULL,
  PRIMARY KEY (TERM_SQNO),
  KEY IX_HP_TERM_01 (TERM_KND_CD, USE_YN, APLY_BGNG_DT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='약관/개인정보처리방침';

SET FOREIGN_KEY_CHECKS = 1;
